qbook/urls.py
from django.contrib import admin
from django.urls import path
from .views import HomeView, TrendingView, SubscriptionsView, LatestQuestionsFeed
urlpatterns = [
    path('', HomeView, name='home'),
    path('trending/', TrendingView, name='trending'),
    path('subscriptions/', SubscriptionsView, name='subscriptions'),
    path('latest-questions/', LatestQuestionsFeed(), name='latest-questions'),
]

qbooknew/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('accounts.urls')),
    path('', include('answer.urls')),
    path('', include('question.urls')),
    path('', include('votes.urls')),
    path('', include('qbook.urls')),
    path('', include('user.urls')),
]

user/urls.py
from django.urls import path
from .views import  AskerView, EditProfileView, DeleteProfileView
urlpatterns = [
    path('editprofile/<int:pk>/', EditProfileView.as_view(), name='edit_profile'),
    path('deleteprofile/<int:pk>/', DeleteProfileView.as_view(), name='delete_profile'),
    path('askers/<int:pk>/', AskerView, name='asker'),
    # path('follow/<int:pk>/', UserFollowView, name='user_follow'),
]

qbook/models.py
from django.db import models

# Create your models here.

votes/models.py
from django.db import models
from django.contrib.auth.models import User
from question.models import Question
from answer.models import Answer
# Create your models here.
class QuestionUpVote(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    date = models.DateTimeField(auto_now_add=True)


class QuestionDownVote(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    date = models.DateTimeField(auto_now_add=True)


class AnswerUpVote(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    answer = models.ForeignKey(Answer, on_delete=models.CASCADE)
    date = models.DateTimeField(auto_now_add=True)


class AnswerDownVote(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    answer = models.ForeignKey(Answer, on_delete=models.CASCADE)
    date = models.DateTimeField(auto_now_add=True)

qbook/forms.py
from django import forms

SORT_TAGS = [
    ('N', 'Date added(newest)'),
    ('P', 'Most popular'),
    ('O', 'Date added(oldest)'),


]


class SortForm(forms.Form):
    tag = forms.ChoiceField(choices=SORT_TAGS)

qbook/views.py
from django.shortcuts import render
from question.models import Question
from .forms import SortForm
from django.db.models import Count
from votes.models import QuestionUpVote, QuestionDownVote
# Create your views here.
def HomeView(request):
    questions = Question.objects.all().order_by('-date')
    if request.method == 'POST':
        form = SortForm(request.POST)
        if form.is_valid():
            form_tag = form.cleaned_data['tag']
            if form_tag == 'O':
                questions = questions.order_by('date')
            if form_tag == 'N':
                questions = questions.order_by('-date')
            if form_tag == 'P':
                questions = questions.annotate(upvotes=Count(
                    'questionupvote')).order_by('-views', '-upvotes')
    else:
        form = SortForm()
    return render(request, 'qbook/home.html', {'questions': questions, 'form': form})


def TrendingView(request):
    questions = Question.objects.all()
    for question in questions:
        question.upvotes = QuestionUpVote.objects.filter(
            question=question).count()
        question.downvotes = QuestionDownVote.objects.filter(
            question=question).count()
    return render(request, 'qbook/trending.html', {'questions': questions})


def SubscriptionsView(request):
    questions = Question.objects.all()
    for question in questions:
        question.upvotes = QuestionUpVote.objects.filter(
            question=question).count()
        question.downvotes = QuestionDownVote.objects.filter(
            question=question).count()
    return render(request, 'qbook/subscriptions.html', {'questions': questions})

from django.contrib.syndication.views import Feed
from django.urls import reverse
from question.models import Question

class LatestQuestionsFeed(Feed):
    title = "Latest questions"
    link = "/sitenews/"
    description = "Latest questions askeed by users."

    def items(self):
        return Question.objects.order_by('-date')[:5]

    def item_title(self, item):
        return item.tag

    def item_description(self, item):
        return item.body

    # item_link is only needed if NewsItem has no get_absolute_url method.
    def item_link(self, item):
        return reverse('question_single', args=[item.pk])

qbook/templates/qbook/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />

    <!-- Bootstrap CSS -->
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6"
      crossorigin="anonymous"
    />
    {% block title %}
    <title>replace me</title>
    {% endblock %} {% block styles %} {% endblock %}
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'home' %}">QueBook</a>
        <button
          class="navbar-toggler"
          type="button"
          data-bs-toggle="collapse"
          data-bs-target="#navbarSupportedContent"
          aria-controls="navbarSupportedContent"
          aria-expanded="false"
          aria-label="Toggle navigation"
        >
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <li class="nav-item">
              <a class="nav-link" href="{% url 'question_form' %}"
                >Ask Question</a
              >
            </li>
          </ul>
          <ul class="d-flex">
            {% if request.user.is_authenticated %}
            <li class="nav-item">
              <a class="nav-link" href="{% url 'asker' request.user.id %}">
                {% if request.user.askerprofile.photo %}
                <img
                  src="{{request.user.askerprofile.photo.url}}"
                  width="30px"
                  height="30px"
                  style="margin-right: 3px"
                />{% endif %}{{request.user.username}}
              </a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'logout' %}">Sign Out</a>
            </li>
            {% else %}
            <li class="nav-item">
              <a class="nav-link" href="{% url 'login' %}">Sign In</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'signup' %}">Sign Up</a>
            </li>
            {% endif %}
          </ul>
        </div>
      </div>
    </nav>
    <!-- <nav class="navbar navbar-expand-lg navbar-light">
      <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'home' %}">QueBook</a>
        <button
          class="navbar-toggler"
          type="button"
          data-bs-toggle="collapse"
          data-bs-target="#navbarSupportedContent"
          aria-controls="navbarSupportedContent"
          aria-expanded="false"
          aria-label="Toggle navigation"
        >
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <li class="nav-item">
              <a class="nav-link" href="{% url 'question_form' %}"
                >Ask Question</a
              >
            </li>
            <li></li>
            {% if request.user.is_authenticated %}
            <li class="nav-item">
              <a class="nav-link" href="{% url 'asker' request.user.id %}"
                >{{user.username}}</a
              >
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'logout' %}">Sign Out</a>
            </li>
            {% else %}
            <li class="nav-item">
              <a class="nav-link" href="{% url 'login' %}">Sign In</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'signup' %}">Sign Up</a>
            </li>
            {% endif %}
          </ul>
        </div>
      </div>
    </nav> -->
    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-JEW9xMcG8R+pH31jmWH6WWP0WintQrMb4s7ZOdauHnUtxwoG2vI5DkLtS3qm9Ekf"
      crossorigin="anonymous"
    ></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.1/dist/umd/popper.min.js" integrity="sha384-SR1sx49pcuLnqZUnnPwx6FCym0wLsk5JZuNx2bPPENzswTNFaQU1RDvt3wT4gWFG" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.min.js" integrity="sha384-j0CNLUeiqtyaRmlzUHCPZ+Gy5fQu0dQ6eZ/xAww941Ai1SxSY+0EQqNXNE6DZiVc" crossorigin="anonymous"></script>
    -->
    <div class="container-fluid">
      {% block tags %}
      <div style="padding-top: 10px">
        <a href="{% url 'tag_questions' 'Science' %}"
          ><button style="margin: 5px" type="submit" class="btn btn-primary">
            Science
          </button></a
        >
        <a href="{% url 'tag_questions' 'Mathematics' %}"
          ><button style="margin: 5px" type="submit" class="btn btn-primary">
            Mathematics
          </button></a
        >
        <a href="{% url 'tag_questions' 'History' %}"
          ><button style="margin: 5px" type="submit" class="btn btn-primary">
            History
          </button></a
        >
        <a href="{% url 'tag_questions' 'Geography' %}"
          ><button style="margin: 5px" type="submit" class="btn btn-primary">
            Geography
          </button></a
        >
        <a href="{% url 'tag_questions' 'ICT' %}"
          ><button style="margin: 5px" type="submit" class="btn btn-primary">
            ICT
          </button></a
        >
        <a href="{% url 'tag_questions' 'Sinhala' %}"
          ><button style="margin: 5px" type="submit" class="btn btn-primary">
            Sinhala
          </button></a
        >
        <a href="{% url 'tag_questions' 'English' %}"
          ><button style="margin: 5px" type="submit" class="btn btn-primary">
            English
          </button></a
        >
        <a href="{% url 'tag_questions' 'Agriculture' %}"
          ><button style="margin: 5px" type="submit" class="btn btn-primary">
            Agriculture
          </button></a
        >
        <a href="{% url 'tag_questions' 'Commerce' %}"
          ><button style="margin: 5px" type="submit" class="btn btn-primary">
            Commerce
          </button></a
        >
        <a href="{% url 'tag_questions' 'Buddhism' %}"
          ><button style="margin: 5px" type="submit" class="btn btn-primary">
            Buddhism
          </button></a
        >
        <a href="{% url 'tag_questions' 'Dance' %}"
          ><button style="margin: 5px" type="submit" class="btn btn-primary">
            Dance
          </button></a
        >
        <a href="{% url 'tag_questions' 'Art' %}"
          ><button style="margin: 5px" type="submit" class="btn btn-primary">
            Art
          </button></a
        >
        <a href="{% url 'tag_questions' 'Drama' %}"
          ><button style="margin: 5px" type="submit" class="btn btn-primary">
            Drama
          </button></a
        >
        <a href="{% url 'tag_questions' 'Music' %}"
          ><button style="margin: 5px" type="submit" class="btn btn-primary">
            Music
          </button></a
        >
        <a href="{% url 'tag_questions' 'Health ' %}"
          ><button style="margin: 5px" type="submit" class="btn btn-primary">
            Health
          </button></a
        >
        <a href="{% url 'tag_questions' 'Tamil' %}"
          ><button style="margin: 5px" type="submit" class="btn btn-primary">
            Tamil
          </button></a
        >
      </div>
      {% endblock %} {% block content %} {% endblock %}
    </div>
  </body>
</html>

qbook/templates/qbook/home.html
{% extends 'qbook/base.html' %} {% block title %}
<title>QBook</title>
{% endblock %} {% block styles %}
<style>
  .center {
    margin: 50px auto;
    width: 70%;
    text-align: justify;
  }
  h3,
  h4,
  p,
  h5 .btn-holder {
    text-align: justify;
  }
  a {
    color: black;
    text-decoration: none;
  }
  ul {
    list-style-type: none;
  }
  p {
    color: rgb(81, 83, 85);
  }
</style>
{% endblock %}{% block content %}
<div class="center">
  <h3>All Questions</h3>
  <br />
  <form method="POST" action="">
    {% csrf_token %}
    <div class="mb-3">
      <label class="form-label">Sort By</label>
      {{ form.tag }}
      <button type="submit" class="btn btn-info btn-sm">Sort</button>
    </div>
  </form>
  <br />
  <div class="pt-2"></div>
  {% if questions %} {% for question in questions %}
  <a href="{% url 'question_single' question.pk %}">
    {% if question.heading %}
    <h3>{{question.heading}}</h3>
    <br />
    {% endif %}
    <h6>{{question.body|truncatechars:500}}</h6>
  </a>
  <p>
    <a href="{% url 'tag_questions' question.tag %}"
      ><button type="submit" class="btn btn-warning btn-sm">
        {{question.tag}}
      </button></a
    >
    Asked By
    <a href="{% url 'asker' question.user.id %}"
      >{% if question.user.askerprofile.photo %}
      <img
        src="{{question.user.askerprofile.photo.url}}"
        width="30px"
        height="30px"
        style="margin-right: 3px"
      />{% endif %} {{ question.user.username }}</a
    >
    on {{ question.date }}
    <span class="badge alert-success"
      >{{question.questionupvote_set.count}} upvotes
    </span>
    <span class="badge alert-danger"
      >{{question.questiondownvote_set.count}} downvotes
    </span>
    <span class="badge alert-secondary">{{question.views}} views</span>
  </p>
  <hr />
  <br />
  {% endfor %} {% endif %}
</div>
{% endblock %}

qbook/templates/qbook/subscriptions.html
{% extends 'qbook/base.html' %} {% block title %}
<title>Subscriptions</title>
{% endblock %} {% block styles %}
<style>
  .center {
    margin-right: 200px;
    margin-top: 50px;
    text-align: justify;
  }

  ul {
    list-style-type: none;
  }
</style>
{% endblock %} {% block content %}

<p><b>Recent</b></p>
<p><b>This Week</b></p>
<p><b>This Month</b></p>
<p><b>Older</b></p>

{% if questions %} {% for question in questions %}
<a href="{% url 'question_single' question.pk %}"
  ><h4>{{question.body|truncatechars:500}}</h4></a
>
<p>
  <a href="{% url 'tag_questions' question.tag %}"
    ><button type="submit" class="btn btn-warning btn-sm">
      {{question.tag}}
    </button></a
  >
  Asked By
  <a href="{% url 'asker' question.user.id %}">{{ question.user.username }}</a>
  on {{ question.date }} upvotes- {{question.upvotes}} downvotes-
  {{question.downvotes}} views- {{question.views}}
</p>
<hr />
{% endfor %} {% endif %} {% endblock %}

qbook/templates/qbook/trending.html
{% extends 'qbook/base.html' %} {% block title %}
<title>Trending</title>
{% endblock %} {% block styles %}
<style>
  .center {
    margin-right: 200px;
    margin-top: 50px;
    text-align: justify;
  }

  ul {
    list-style-type: none;
  }
</style>
{% endblock %} {% block content %}

<p><b>Trending Questions</b></p>

{% if questions %} {% for question in questions %}
<a href="{% url 'question_single' question.pk %}"
  ><h4>{{question.body|truncatechars:500}}</h4></a
>
<p>
  <a href="{% url 'tag_questions' question.tag %}"
    ><button type="submit" class="btn btn-warning btn-sm">
      {{question.tag}}
    </button></a
  >
  Asked By
  <a href="{% url 'asker' question.user.id %}">{{ question.user.username }}</a>
  on {{ question.date }} upvotes- {{question.upvotes}} downvotes-
  {{question.downvotes}} views- {{question.views}}
</p>
<hr />
{% endfor %} {% endif %} {% endblock %}